version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecotask
      POSTGRES_PASSWORD: ecotask
      POSTGRES_MULTIPLE_DATABASES: ecotask,sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://ecotask:ecotask@db:5432/ecotask
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=ecotask
      - SONAR_JDBC_PASSWORD=ecotask
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db

  sonar-scanner:
    image: newtmitch/sonar-scanner:latest
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=sqa_5b9c03d9462812b245564e346ac42df9e64864c2
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - sonarqube

volumes:
  postgres_data:
  grafana_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: 