apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecotask-backend
  namespace: ecotask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecotask-backend
  template:
    metadata:
      labels:
        app: ecotask-backend
    spec:
      containers:
      - name: backend
        image: icare741/ecotask-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ecotask-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ecotask-backend
  namespace: ecotask
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: ecotask-backend 